### ISSUE TITLE
Need turkey map

### ISSUE THREAD

**Issue by hochocki** [Akaflieg-Freiburg/enrouteServer#14]
Hi,
I am huseyin. I am a student pilot in turkey. I am flying at ltbo airport i need turkey map. Thank you.

**Comment by kebekus** [comment]
Thanks for your report. Please have a look at the following page:

https://akaflieg-freiburg.github.io/enroute/FAQ/#there-are-no-maps-for-my-country-can-you-please-add-them

There, I explain what needs to be done to add a country.
