### ISSUE TITLE
Afghanistan aviation maps

### ISSUE THREAD

**Issue by Yasinbehzad** [Akaflieg-Freiburg/enrouteServer#15]
I want to download Afghanistan country in Asia aviation maps.
Thank you 
Best regards.

**Comment by kebekus** [comment]
Dear Yasinbehzad,

thanks. Please have a look at 

- https://akaflieg-freiburg.github.io/enroute/FAQ/#there-are-no-maps-for-my-country-can-you-please-add-them

where I outline what needs to be done.

Best,

Stefan Kebekus.
