### ISSUE TITLE
Hello from Uruguay everyone

### ISSUE THREAD

**Issue by FAU610** [Akaflieg-Freiburg/enrouteServer#16]
Hello! I finished here meanwhile I was trying to download a aviation map from UY.

I saw that there is not any map about my country but I have the AIP so I think that maybe it could help. I'm an air force student and I am finishing the navigation part of the flight course, but I am sure that it will help to other one and to you in learning about our FIR.

**Comment by kebekus** [comment]
Dear FAU610,

unfortunately, UY airspace is not covered by openAIP.net, the public database that I use to generate maps. Data in openAIP is provided by volunteers; please get in touch with the people at openAIP if you are interested to help. Once the data becomes available, I will be happy to include maps of UY.

Best

Stefan.
