### ISSUE TITLE
Map Bolivia South America

### ISSUE THREAD

**Issue by cgweise** [Akaflieg-Freiburg/enrouteServer#17]
Please include the map of Bolivia BO

**Comment by kebekus** [comment]
Dear cgweise,

unfortunately, Bolivian airspace is not covered by openAIP.net, the public database that I use to generate maps. Data in openAIP is provided by volunteers; please get in touch with the people at openAIP if you are interested to help. Once the data becomes available, I will be happy to include maps of Bolivia.

Best

Stefan.
