### ISSUE TITLE
Albania and Montenegro Maps 

### ISSUE THREAD

**Issue by Prosdi** [Akaflieg-Freiburg/enrouteServer#18]
Dear Github,

The first time, I would like to compliment you about the Enroute app. It is very useful and I love using it during my flights. Could you please upload the maps that I mention in the email subject?

Kind regards, 

Marco

**Comment by kebekus** [comment]
Thank you for your request. Could you please have a look at the [following URL}(https://akaflieg-freiburg.github.io/enroute/FAQ/#there-are-no-maps-for-my-country-can-you-please-add-them) and check if the conditions are fulfilled? If yes, then I'd be happy to add the countries.

**Comment by kebekus** [comment]
I close this issue because of no replay. Please feel free to re-open anytime.
