### ISSUE TITLE
Add Japanese Map

### ISSUE THREAD

**Issue by nazebeth** [Akaflieg-Freiburg/enrouteServer#19]
Hello,

Please add Japanese map to the list of Enroute Flight Navigation. I just added a small airfield for pure gliders and powered gliders to OpenAIP. I think Japanese data in OpenAIP is reliable. I'm going to update the navaids and airports if necessary.

**Comment by kebekus** [comment]
Maps is now available.

**Comment by nazebeth** [comment]
Hi Stefan,

Thank you for your quick support.

Btw, what kind of time scale are you going to update the aviation data from
OpenAIP? I think I will take occasion to update the Japanese aviation data
of OpenAIP.

And is there another way you could accept the donation except bank
transfer? As you know, the overseas remittance is very complicated and need
to pay the commission rate.

Best,

Kei

2021年4月25日(日) 22:28 Stefan Kebekus ***@***.***>:

**Comment by kebekus** [comment]
Dear Kei,

> Btw, what kind of time scale are you going to update the aviation data from OpenAIP? I think I will take occasion to update the Japanese aviation data of OpenAIP.
>
I generate new maps every Monday morning (Berlin time). You contributions to openAIP would be extremely welcome!

> And is there another way you could accept the donation except bank transfer? As you know, the overseas remittance is very complicated and need to pay the commission rate.
>
Thank you for pointing this out. Again, your contributions are greatly appreciated. I will set up a proper PayPal page for the flight club, but this will take some time. For now, you could use PayPal to send the donation to stefan.kebekus@web.de, I will then forward to donatation to the club.

Best wishes -- stay healty,

Stefan.

PS: Around 2000, I lived in Kyoto for one year. I still have very fond memories of the place and its people…

**Comment by nazebeth** [comment]
Hi Stefan,

I will upload the Navaids data to OpenAIP soon. Currently only 4 Navs
of Japan stored in OpenAIP.

One year in Kyoto was good experience for you. Kyoto is a bit
different and attractive town for even us.

I sent 3,000 yen through Paypal. Take a look at your account later.

Regards,

Kei

2021年4月28日(水) 17:54 Stefan Kebekus ***@***.***>:
