### ISSUE TITLE
Add Paraguay maps

### ISSUE THREAD

**Issue by Julioalbertini** [Akaflieg-Freiburg/enrouteServer#23]
Hello. I'm a private pilot from Paraguay. We are waiting for Paraguay updates. The maps are not the newest and updated but they're correct.

**Comment by kebekus** [comment]
Dear Julioalbertini,

thank you for your request. I had a look at the openAIP maps for Paraguay … and it seems that the data is very incomplete: no airspace information at all, no data about runway orientation. As a result, Paraguay cannot be added at this point.

I am sorry that I have no better news. You are welcome to contact people at openAIP if you would like to help to make their map complete. As soon as better data is available, I will be happy to add your country.

Best,

Stefan Kebekus.
