### ISSUE TITLE
Chile maps and waypoints

### ISSUE THREAD

**Issue by Alemanchileno** [Akaflieg-Freiburg/enrouteServer#25]
Chile maps based on AIP CHILE are ok. Data shown is accurate and renewed every 2 years at least. 
Please include it on your library.

**Comment by kebekus** [comment]
Dear Alemanchileno,

please correct me if I am wrong, but it seems to me that the openAIP database does not know about Chilean airspace. Have a look at http://maps.openaip.net/?destination=http://www.openaip.net 

I am closing this issue for now. Feel free to re-open.

Best,

Stefan.
