### ISSUE TITLE
Falkland Islands

### ISSUE THREAD

**Issue by Roobarb72** [Akaflieg-Freiburg/enrouteServer#26]
Hello, I wonder if it would be possible to add the Falkland Islands to your downloadable maps please? I have checked the openAIP and all appears well. I'm a frequent flyer based here.
Many thanks and best regards, Andrew

**Comment by kebekus** [comment]
Dear Roobarb72,

Done. To check the new map out, open the main menu and go to "Library/Maps and Data". You may need to use the three-point menu at the top-right of the screen to update the list of available maps. Once this is done, you find "Falkland Islands" under "South America".

Note: There is no specific base map for the Falklands, so please use Argentina instead. Also, it seems to me that the Islands are covered by a CTR that belongs to Argentina. Install the Argentina aviation map if you wish to see it.

Best wishes from the Black Forest,

Stefan.

PS: Please help to improve openAIP by adding data (such as RWY orientation) to the airfields and landing strips of your island.

**Comment by Roobarb72** [comment]
Perfect Stefan, thanks ever so much!

Regards, Andrew
