### ISSUE TITLE
Add Israel map

### ISSUE THREAD

**Issue by Lidor86** [Akaflieg-Freiburg/enrouteServer#34]
Could you please add support for Israel maps?
Had a look on the openAIP maps and it looks pretty accurate
Thank you!

**Comment by kebekus** [comment]
@Lidor86 Thanks. I am confused about your e-mail, though. When I look at the openAIP map, I see hardly any airspaces. That is probably not correct, is it?

**Comment by kebekus** [comment]
Closing this issue because Israeli airspace seem unavailable in openAIP.
