### ISSUE TITLE
Addition of country data

### ISSUE THREAD

**Issue by thejunaid** [Akaflieg-Freiburg/enrouteServer#35]
Hi, I am Junaid. I am a helicopter pilot. I have checked the data of my country on open aip. The data looks good enough to fly vfr. I request to add the data of India in your  flight navigation app please. Thank you.

**Comment by kebekus** [comment]
Dear Junaid,

I am confused. For all I see, openAIP does not contain any airspace information for India. 

I am closing this issue now. Please correct me if I am wrong, and I will be happy to re-open and work on the problem.

Best,

Stefan.
