### ISSUE TITLE
South america maps

### ISSUE THREAD

**Issue by Impudent27** [Akaflieg-Freiburg/enrouteServer#37]
Can u please add more maps , there are  a lot  of countries in South América, i really apreciate if you can add the colombian map

**Comment by kebekus** [comment]
@Impudent27 I will be glad to add more maps if the requirements are satisfied. Could you please have a look at 

https://akaflieg-freiburg.github.io/enroute/FAQ/#there-are-no-maps-for-my-country-can-you-please-add-them

and tell me if the openAIP data covers Columbia sufficiently well? If not, you are of course welcome to contact people at openAIP and to add the potentially missing data. This has recently happened with Madagascar, where I was able to add a map in less than a week after the data became available.

Best,

Stefan.

**Comment by Impudent27** [comment]
I just checked openaip and looks pretty good, everything its on their place, navaids seems good. So it's properly to upload the Columbian map, it will help me a lot, on my major. By the way thanks for answering @kebekus, I hope it will be done as soon as possible:)

**Comment by kebekus** [comment]
@Impudent27 Understood. To help me understand and assess the situation, could you please send me a scan (or a few readable pictures taken by mobile phone) of the official ICAO map for Columbia? It might be easiest to send them by e-mail to stefan.kebekus@gmail.com

You don't have to scan the whole map, a few snapshots from one or two regions will suffice.

**Comment by Impudent27** [comment]
Done, I could find some charts ,  i hope it will help, looking for ur answer @kebekus

**Comment by kebekus** [comment]
@Impudent27 Thank you for the files. These are however not the correct maps. I need the standard ICAO map for VFR flights in Columbia that shows the relevant airspaces of your country.

**Comment by kebekus** [comment]
Done. Columbia is available now.
