### ISSUE TITLE
Show vertical airspace boundaries in map

### ISSUE THREAD

**Issue by kebekus** [Akaflieg-Freiburg/enrouteServer#41]
Title says it all…

**Comment by Dzordzik** [comment]
One of most usable feature in navi apps. +1000 for implementation as priority. (I know about time issues).

**Comment by fbbln** [comment]
I was just about to request this as a feature improvement.
Especially flying around large Airports (EDDB), this would help tremendously!

**Comment by kebekus** [comment]
Implemented in v2.30.16, which appeared a few minutes ago.

@Dzordzik @fbbln Enjoy!

**Comment by fbbln** [comment]
@kebekus This is really cool! Thanks!

**Comment by kebekus** [comment]
It's been my pleasure

**Comment by kebekus** [comment]
It's been my pleasure
