### ISSUE TITLE
Map of Qatar

### ISSUE THREAD

**Issue by Gerpinz** [Akaflieg-Freiburg/enrouteServer#42]
would you please add the map of Qatar, I checked the aeronautical chart at openiap and it is accuate enough for use. I'm a helicopter pilot flying in this region and I will appreciate the update to the Enroute Navigation app.
thank you very much.

**Comment by kebekus** [comment]
@Gerpinz Roger. I had a look and will add a map of Qatar. Give me a few days for that.

**Comment by kebekus** [comment]
@Gerpinz Done. I have added maps for Bahrain, Qatar and the Emirates. Can you please check those maps out and give me some feedback? Here's what to do:

- If you have installed any maps during the last few days, please uninstall them first. I had some difficulties generating the base maps, and some defective maps for Bahrain, Qatar and the Emirates were accidentally uploaded to the server.
- In **Enroute Flight Navigation**, open the main menu and go to "Library/Maps and Data". The page "Maps and Data" will open.
- Open the three-dot-menu in the upper right corner and choose "Update List of Maps and Data". By default, the app looks only once per week if new maps are available and might not have noticed the new maps yet.
- Find the maps in the section "Asia" and download them to your liking.

Best wishes · Happy new year,

Stefan.

**Comment by kebekus** [comment]
Closed for inactivity and lack of communication.
